apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
    ports:
    - port: 8088
      targetPort: 80
      nodePort: 30080  # <- You can change this to a port between 30000–32767
    selector:
      app: nginx
    type: NodePort  

