apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim  
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: manual     # Must match the PV storageClass

