apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-pod
  template:
    metadata:
      labels:
        app: registry-pod
    spec:
      containers:
        - name: registry-container
          image: 192.168.3.1:5000/registry-image
          ports:
            - containerPort: 8888
          imagePullPolicy: Always  
         
---
apiVersion: v1
kind: Service
metadata:
  name: registry-srv
spec:
  selector:
    app: registry-pod
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30008
  type: NodePort   
